version: '2'
services:
  spring-web-reactive:
    image: java:openjdk-8u91
    hostname: "openjdk8.dev"
    container_name: spring-web-reactive
    volumes:
      - ./build:/opt/spring
    working_dir: /opt/spring
    command: tail -f /dev/null
#    command: java -Xmx50m -Xss256k -jar hello-world-1.0-SNAPSHOT.jar
    mem_limit: 150m
    memswap_limit: 0
